// This class is generated by flutter_lang. 
// Do not modify this file manually. 

import 'package:flutter/cupertino.dart';

class TranslationsHelperChangeProvider with ChangeNotifier { 
  Locale currentLocale = const Locale('en'); 

  Locale get getCurrentLocale => currentLocale; 

  TranslationsHelperChangeProvider({required String currentLangaugeCode}) { 
    currentLocale = Locale(currentLangaugeCode); 
  } 

  void changeLanguage(String languageCode) { 
    currentLocale = Locale(languageCode); 
    notifyListeners(); 
  } 
} 
