class GeneratorStateProvider {
  final String parentClass;
  final String defaultLanguage;
  String _classData = "";

  String get generatedClassData => _classData;

  GeneratorStateProvider({
    required this.parentClass,
    required this.defaultLanguage,
  });

  generate() {
    _classData += "";
    _classData += "// This class is generated by flutter_lang. \n";
    _classData += "// Do not modify this file manually. \n\n";
    _classData += "import 'package:flutter/cupertino.dart';\n\n";

    _classData += "class ${parentClass}ChangeProvider with ChangeNotifier { \n";
    _classData +=
        "  Locale currentLocale = const Locale('$defaultLanguage'); \n\n";

    _classData += "  Locale get getCurrentLocale => currentLocale; \n\n";

    _classData +=
        "  ${parentClass}ChangeProvider({required String currentLangaugeCode}) { \n";
    _classData += "    currentLocale = Locale(currentLangaugeCode); \n";
    _classData += "  } \n\n";

    _classData += "  void changeLanguage(String languageCode) { \n";
    _classData += "    currentLocale = Locale(languageCode); \n";
    _classData += "    notifyListeners(); \n";
    _classData += "  } \n";
    _classData += "} \n";
  }
}
