class GeneratorStateGetX {
  final String parentClass;
  final String defaultLanguage;
  String _classData = "";

  String get generatedClassData => _classData;

  GeneratorStateGetX({
    required this.parentClass,
    required this.defaultLanguage,
  });

  generate() {
    _classData += "";
    _classData += "// This class is generated by flutter_lang. \n";
    _classData += "// Do not modify this file manually. \n\n";
    _classData += "import 'package:flutter/cupertino.dart';\n\n";
    _classData += "import 'package:get/get.dart';\n\n";

    _classData +=
        "class ${parentClass}GetXController extends GetxController { \n";
    _classData +=
        "  Rx<Locale> currentLocale = Rx(const Locale('$defaultLanguage')); \n\n";

    _classData += "  Locale get getCurrentLocale => currentLocale.value; \n\n";

    _classData +=
        "  ${parentClass}GetXController({required String currentLangaugeCode}) { \n";
    _classData += "    currentLocale.value= Locale(currentLangaugeCode); \n";
    _classData += "  } \n\n";

    _classData += "  void changeLanguage(String languageCode) { \n";
    _classData += "    currentLocale.value= Locale(languageCode); \n";
    _classData += "  } \n";
    _classData += "} \n";
  }
}
