targets:
  $default:
    builders:
      generate_flutter_languages:
        generate_for:
          - lib/**flutter_lang.dart

builders:
  generate_flutter_languages:
    target: ":flutter_lang" # Generator name
    import: "package:flutter_lang/generators.dart"
    builder_factories: ["generateFlutterLanguages"] # Builder name(BuilderOption) this is a definition
    build_extensions: { "**flutter_lang.dart": [".core.g.dart", ".lang.g.dart", ".state.g.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen"]
    defaults:
      generate_for:
        # Only apply to .dart files in the web directory
        include:
          - lib/**flutter_lang.dart
