name: flutter_lang
description: Flutter Localization package(intented to work with other packages)
version: 1.0.0
homepage: anees4ever.github.io/flutter_lang
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0

  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  dart_flutter_team_lints: ^2.0.0