/// This class is generated by flutter_lang. 
/// Do not modify this file manually. 

import 'package:flutter/cupertino.dart';

class FlutterLanguageChangeProvider with ChangeNotifier { 
  Locale currentLocale = const Locale('en'); 

  Locale get getCurrentLocale => currentLocale; 

  FlutterLanguageChangeProvider({required String currentLangaugeCode}) { 
    currentLocale = Locale(currentLangaugeCode); 
  } 

  void changeLocale(String locale) { 
    currentLocale = Locale(locale); 
    notifyListeners(); 
  } 
} 
